# 解析度與視窗
BASE_WIDTH = 3840
BASE_HEIGHT = 2160
WINDOW_TITLE = "NIKKE"
STOP_HOTKEY = "ctrl+1"
HORIZONTAL_SPACING = 50
ACTION_DELAY = 1.2

# 玩家座標
PLAYER1_COORD_ABS = [1671, 691]
PLAYER2_COORD_ABS = [2175, 669]
EXIT_COORD_ABS = [2370, 681]
TEAM_COORDS_ABS = [
    [1515, 1064],
    [1734, 1064],
    [1928, 1064],
    [2112, 1064],
    [2303, 1064]
]

# 截圖區域 (主隊伍)
SCREENSHOT_LEFT_ABS = 1433
SCREENSHOT_TOP_ABS = 1134
SCREENSHOT_RIGHT_ABS = 2417
SCREENSHOT_BOTTOM_ABS = 1530
# SCREENSHOT_REGION 由程式自動計算

# 玩家資訊區域
PLAYER_INFO_LEFT_ABS = 1433
PLAYER_INFO_TOP_ABS = 768
PLAYER_INFO_RIGHT_ABS = 2417
PLAYER_INFO_BOTTOM_ABS = 963
# PLAYER_INFO_REGION 由程式自動計算

# 詳細資訊點擊座標
PLAYER_DETAILINFO_2_ABS = [1560, 866]
PLAYER_DETAILINFO_3_ABS = [2200, 2000]
PLAYER_DETAILINFO_CLOSE_ABS = [3500, 200]

# 玩家資訊2區域
PLAYER_INFO_2_LEFT_ABS = 1433
PLAYER_INFO_2_TOP_ABS = 1344
PLAYER_INFO_2_RIGHT_ABS = 2417
PLAYER_INFO_2_BOTTOM_ABS = 1529
# PLAYER_INFO_2_REGION 由程式自動計算

# 玩家資訊3區域
PLAYER_INFO_3_LEFT_ABS = 1433
PLAYER_INFO_3_TOP_ABS = 1768
PLAYER_INFO_3_RIGHT_ABS = 2417
PLAYER_INFO_3_BOTTOM_ABS = 1850
# PLAYER_INFO_3_REGION 由程式自動計算

# 民意區域
PEOPLE_VOTE_LEFT_ABS = 1395
PEOPLE_VOTE_TOP_ABS = 285
PEOPLE_VOTE_RIGHT_ABS = 2433
PEOPLE_VOTE_BOTTOM_ABS = 1944
# PEOPLE_VOTE_REGION 由程式自動計算

# Mode 2 專用座標
PLAYER1_COORD_ABS_M2 = [1540, 1083]
PLAYER2_COORD_ABS_M2 = [2176, 1083]
RESULT_SCREENSHOT_LEFT_ABS = 1600
RESULT_SCREENSHOT_TOP_ABS = 958
RESULT_SCREENSHOT_RIGHT_ABS = 2109
RESULT_SCREENSHOT_BOTTOM_ABS = 1651
# RESULT_SCREENSHOT_REGION 由程式自動計算
