name: Build EXE

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Install dependencies
        run: pdm install

      - name: Build EXE
        run: pdm run nikke-cjjc-automator-build-pyd
    
      - name: Upload EXE to Actions
        uses: actions/upload-artifact@v3
        with:
          name: nikke-cjjc-automator-exe
          path: dist/nikke-cjjc-automator.exe
