name: Build EXE

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UPX  # pyinstaller will automatically use UPX if it's available (in $PATH)
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Install dependencies
        run: pdm install

      - name: Build EXE
        run: pdm run nikke-cjjc-automator-build-pyd

    #   - name: Compress executable with UPX
    #     uses: crazy-max/ghaction-upx@v3
    #     with:
    #       version: latest
    #       files: |
    #         dist/nikke-cjjc-automator.exe
    #       args: -9 -f --lzma
    
      - name: Upload EXE to Actions
        uses: actions/upload-artifact@v4
        with:
          name: nikke-cjjc-automator-exe
          path: dist/nikke-cjjc-automator.exe
