name: Build and Release EXE

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
      - main
  workflow_dispatch:

env:
  INSTALL_UPX: ${{ vars.INSTALL_UPX }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set default variable
        run: echo "INSTALL_UPX=${INSTALL_UPX:-false}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install UPX  # pyinstaller will automatically use UPX if it's available (in $PATH)
        if: env.INSTALL_UPX == 'true'
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Install dependencies
        run: pdm install

      - name: Build EXE
        run: pdm run nikke-cjjc-automator-build-pyd

      - name: Upload EXE to Actions
        uses: actions/upload-artifact@v4
        with:
          name: nikke-cjjc-automator-exe
          path: dist/nikke-cjjc-automator.exe

      - name: Generate CHANGELOG for Release
        if: startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        run: |
          $changelogFile = "CHANGELOG_${{ github.ref_name || github.sha }}.md"
          "# NIKKE CJJC Automator Release Notes`n" | Out-File -Encoding utf8 $changelogFile
          "`n" | Out-File -Encoding utf8 -Append $changelogFile
          "## Last 10 Commit Messages`n" | Out-File -Encoding utf8 -Append $changelogFile
          git log -10 --pretty=format:"- %s" | Out-File -Encoding utf8 -Append $changelogFile
          echo "CHANGELOG_FILE=$changelogFile" | Out-File -Encoding utf8 -Append $env:GITHUB_ENV

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/nikke-cjjc-automator.exe
          body_path: ${{ github.workspace }}\${{ env.CHANGELOG_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
